'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],wait=ms=>new Promise(r=>setTimeout(r,ms));
const API='https://arduino-cli-python-363946744577.asia-northeast3.run.app/compile';
let ws,port=null,reader=null,serialOpen=false,saveTimer,vars=new Map(),features={};
const DP=[['2','2'],['3','3'],['4','4'],['5','5'],['6','6'],['7','7'],['8','8'],['9','9'],['10','10'],['11','11'],['12','12'],['13','13']],PP=[['3','3'],['5','5'],['6','6'],['9','9'],['10','10'],['11','11']],AP=[['A0','A0'],['A1','A1'],['A2','A2'],['A3','A3'],['A4','A4'],['A5','A5']];
function blocks(){Blockly.Blocks.jikko_start={init(){this.appendDummyInput().appendField('시작하기');this.setNextStatement(true);this.setStyle('event_blocks');this.setHat('cap')}};Blockly.defineBlocksWithJsonArray([
{type:'jikko_delay',message0:'%1 초 기다리기',args0:[{type:'input_value',name:'SEC',check:'Number'}],previousStatement:null,nextStatement:null,style:'control_blocks'},
{type:'jikko_repeat',message0:'%1 번 반복하기',args0:[{type:'input_value',name:'TIMES',check:'Number'}],message1:'%1',args1:[{type:'input_statement',name:'DO'}],previousStatement:null,nextStatement:null,style:'control_blocks'},
{type:'jikko_forever',message0:'무한 반복하기',message1:'%1',args1:[{type:'input_statement',name:'DO'}],previousStatement:null,style:'control_blocks'},
{type:'jikko_if',message0:'만약 %1 (이)라면',args0:[{type:'input_value',name:'COND',check:'Boolean'}],message1:'%1',args1:[{type:'input_statement',name:'DO'}],previousStatement:null,nextStatement:null,style:'control_blocks'},
{type:'jikko_if_else',message0:'만약 %1 (이)라면',args0:[{type:'input_value',name:'COND',check:'Boolean'}],message1:'%1',args1:[{type:'input_statement',name:'DO'}],message2:'아니면 %1',args2:[{type:'input_statement',name:'ELSE'}],previousStatement:null,nextStatement:null,style:'control_blocks'},
{type:'jikko_wait_until',message0:'%1 까지 기다리기',args0:[{type:'input_value',name:'COND',check:'Boolean'}],previousStatement:null,nextStatement:null,style:'control_blocks'},
{type:'jikko_repeat_until',message0:'%1 까지 반복하기',args0:[{type:'input_value',name:'COND',check:'Boolean'}],message1:'%1',args1:[{type:'input_statement',name:'DO'}],previousStatement:null,nextStatement:null,style:'control_blocks'},
{type:'jikko_digital_write',message0:'디지털 핀 %1 을(를) %2',args0:[{type:'field_dropdown',name:'PIN',options:DP},{type:'field_dropdown',name:'STATE',options:[['켜기','HIGH'],['끄기','LOW']]}],previousStatement:null,nextStatement:null,style:'pin_blocks'},
{type:'jikko_pwm_write',message0:'PWM 핀 %1 값을 %2 로 정하기',args0:[{type:'field_dropdown',name:'PIN',options:PP},{type:'input_value',name:'VALUE',check:'Number'}],previousStatement:null,nextStatement:null,style:'pin_blocks'},
{type:'jikko_digital_read',message0:'디지털 핀 %1 값',args0:[{type:'field_dropdown',name:'PIN',options:DP}],output:'Boolean',style:'input_blocks'},
{type:'jikko_analog_read',message0:'아날로그 핀 %1 값',args0:[{type:'field_dropdown',name:'PIN',options:AP}],output:'Number',style:'input_blocks'},
{type:'jikko_servo',message0:'서보모터 핀 %1 각도를 %2 도로 정하기',args0:[{type:'field_dropdown',name:'PIN',options:DP},{type:'input_value',name:'ANGLE',check:'Number'}],previousStatement:null,nextStatement:null,style:'motor_blocks'},
{type:'jikko_ultra',message0:'초음파 TRIG %1 ECHO %2 거리(cm)',args0:[{type:'field_dropdown',name:'TRIG',options:DP},{type:'field_dropdown',name:'ECHO',options:DP}],output:'Number',style:'input_blocks'},
{type:'jikko_tone',message0:'피에조 핀 %1 에 %2 Hz 소리내기',args0:[{type:'field_dropdown',name:'PIN',options:DP},{type:'input_value',name:'FREQ',check:'Number'}],previousStatement:null,nextStatement:null,style:'piezo_blocks'},
{type:'jikko_notone',message0:'피에조 핀 %1 소리 끄기',args0:[{type:'field_dropdown',name:'PIN',options:DP}],previousStatement:null,nextStatement:null,style:'piezo_blocks'},
{type:'jikko_lcd_begin',message0:'I2C LCD 주소 %1 시작하기',args0:[{type:'field_dropdown',name:'ADDR',options:[['0x27','0x27'],['0x3F','0x3F']]}],previousStatement:null,nextStatement:null,style:'lcd_blocks'},
{type:'jikko_lcd_print',message0:'LCD %1 열 %2 행에 %3 출력하기',args0:[{type:'input_value',name:'COL',check:'Number'},{type:'input_value',name:'ROW',check:'Number'},{type:'input_value',name:'TEXT'}],previousStatement:null,nextStatement:null,style:'lcd_blocks'},
{type:'jikko_lcd_clear',message0:'LCD 화면 지우기',previousStatement:null,nextStatement:null,style:'lcd_blocks'},
{type:'jikko_pixel_begin',message0:'네오픽셀 핀 %1 LED 개수 %2 시작하기',args0:[{type:'field_dropdown',name:'PIN',options:DP},{type:'input_value',name:'COUNT',check:'Number'}],previousStatement:null,nextStatement:null,style:'pixel_blocks'},
{type:'jikko_pixel_set',message0:'네오픽셀 %1 번 RGB %2 %3 %4 로 정하기',args0:[{type:'input_value',name:'INDEX',check:'Number'},{type:'input_value',name:'R',check:'Number'},{type:'input_value',name:'G',check:'Number'},{type:'input_value',name:'B',check:'Number'}],previousStatement:null,nextStatement:null,style:'pixel_blocks'},
{type:'jikko_pixel_show',message0:'네오픽셀 보여주기',previousStatement:null,nextStatement:null,style:'pixel_blocks'},
{type:'jikko_serial_begin',message0:'시리얼 통신 속도 %1 로 시작하기',args0:[{type:'field_dropdown',name:'BAUD',options:[['9600','9600'],['57600','57600'],['115200','115200']]}],previousStatement:null,nextStatement:null,style:'serial_blocks'},
{type:'jikko_serial_print',message0:'시리얼에 %1 출력하기',args0:[{type:'input_value',name:'TEXT'}],previousStatement:null,nextStatement:null,style:'serial_blocks'}]);}
const n=(type,input,value)=>({kind:'block',type,inputs:{[input]:{shadow:{type:'math_number',fields:{NUM:value}}}}}),bool=()=>({shadow:{type:'logic_boolean',fields:{BOOL:'TRUE'}}});
function toolbox(){return{kind:'categoryToolbox',contents:[
{kind:'category',name:'이벤트',categorystyle:'event_category',contents:[{kind:'block',type:'jikko_start'}]},
{kind:'category',name:'제어',categorystyle:'control_category',contents:[n('jikko_delay','SEC',1),n('jikko_repeat','TIMES',10),{kind:'block',type:'jikko_forever'},{kind:'block',type:'jikko_if',inputs:{COND:bool()}},{kind:'block',type:'jikko_if_else',inputs:{COND:bool()}},{kind:'block',type:'jikko_wait_until',inputs:{COND:bool()}},{kind:'block',type:'jikko_repeat_until',inputs:{COND:bool()}}]},
{kind:'category',name:'연산',categorystyle:'operator_category',contents:[{kind:'block',type:'math_number'},{kind:'block',type:'math_arithmetic',inputs:{A:{shadow:{type:'math_number',fields:{NUM:1}}},B:{shadow:{type:'math_number',fields:{NUM:1}}}}},{kind:'block',type:'logic_compare',inputs:{A:{shadow:{type:'math_number',fields:{NUM:1}}},B:{shadow:{type:'math_number',fields:{NUM:1}}}}},{kind:'block',type:'logic_operation'},{kind:'block',type:'logic_negate'},{kind:'block',type:'logic_boolean'}]},
{kind:'category',name:'핀',categorystyle:'pin_category',contents:[{kind:'block',type:'jikko_digital_write'},n('jikko_pwm_write','VALUE',128),{kind:'block',type:'jikko_digital_read'},{kind:'block',type:'jikko_analog_read'}]},
{kind:'category',name:'LED',categorystyle:'led_category',contents:[{kind:'block',type:'jikko_digital_write'},n('jikko_pwm_write','VALUE',128)]},
{kind:'category',name:'모터',categorystyle:'motor_category',contents:[n('jikko_servo','ANGLE',90)]},
{kind:'category',name:'입력',categorystyle:'input_category',contents:[{kind:'block',type:'jikko_digital_read'},{kind:'block',type:'jikko_analog_read'},{kind:'block',type:'jikko_ultra'}]},
{kind:'category',name:'피에조부저',categorystyle:'piezo_category',contents:[n('jikko_tone','FREQ',262),{kind:'block',type:'jikko_notone'}]},
{kind:'category',name:'I2C LCD',categorystyle:'lcd_category',contents:[{kind:'block',type:'jikko_lcd_begin'},{kind:'block',type:'jikko_lcd_print',inputs:{COL:{shadow:{type:'math_number',fields:{NUM:0}}},ROW:{shadow:{type:'math_number',fields:{NUM:0}}},TEXT:{shadow:{type:'text',fields:{TEXT:'안녕하세요'}}}}},{kind:'block',type:'jikko_lcd_clear'}]},
{kind:'category',name:'네오픽셀',categorystyle:'pixel_category',contents:[n('jikko_pixel_begin','COUNT',8),{kind:'block',type:'jikko_pixel_set',inputs:{INDEX:{shadow:{type:'math_number',fields:{NUM:0}}},R:{shadow:{type:'math_number',fields:{NUM:255}}},G:{shadow:{type:'math_number',fields:{NUM:0}}},B:{shadow:{type:'math_number',fields:{NUM:0}}}}},{kind:'block',type:'jikko_pixel_show'}]},
{kind:'category',name:'변수',categorystyle:'variable_category',custom:'VARIABLE'},
{kind:'category',name:'문자',categorystyle:'text_category',contents:[{kind:'block',type:'text'},{kind:'block',type:'text_join'}]},
{kind:'category',name:'시리얼',categorystyle:'serial_category',contents:[{kind:'block',type:'jikko_serial_begin'},{kind:'block',type:'jikko_serial_print',inputs:{TEXT:{shadow:{type:'text',fields:{TEXT:'안녕하세요'}}}}}]}
]}}
function theme(){const c={event:['#F2BB35','#D99D12','#C58A00'],control:['#EDA832','#D58B16','#BF7600'],operator:['#55A867','#398A4C','#27733A'],pin:['#DA3F42','#BE292C','#A31C1F'],led:['#B83970','#9E2658','#861B48'],motor:['#9643CC','#7C2DAF','#662291'],input:['#5A5BDD','#4243C3','#3435A7'],piezo:['#5166D9','#384CBF','#2C3CA1'],lcd:['#48A78A','#328C70','#23745C'],pixel:['#E29B2F','#C78116','#AA6B08'],variable:['#53616B','#3D4952','#2E3941'],text:['#5871A9','#405B91','#304777'],serial:['#8B5ADE','#7040C2','#5B2DA7']},bs={};for(const[k,v]of Object.entries(c))bs[k+'_blocks']={colourPrimary:v[0],colourSecondary:v[1],colourTertiary:v[2]};bs.logic_blocks=bs.math_blocks=bs.operator_blocks;bs.variable_dynamic_blocks=bs.variable_blocks;const cs={};for(const[k,v]of Object.entries(c))cs[k+'_category']={colour:v[0]};return Blockly.Theme.defineTheme('jikko',{base:Blockly.Themes.Classic,blockStyles:bs,categoryStyles:cs,componentStyles:{workspaceBackgroundColour:'#FBFCFD',toolboxBackgroundColour:'#FFF',toolboxForegroundColour:'#4D5663',flyoutBackgroundColour:'#F8F9FB',flyoutForegroundColour:'#4D5663',flyoutOpacity:1,scrollbarColour:'#C7CDD4',scrollbarOpacity:.8,insertionMarkerColour:'#74CB63',insertionMarkerOpacity:.45},fontStyle:{family:'Arial, Noto Sans KR, sans-serif',weight:'600',size:12},startHats:true})}
function defaultBlocks(){const x=`<xml xmlns="https://developers.google.com/blockly/xml"><block type="jikko_start" x="40" y="30"><next><block type="jikko_forever"><statement name="DO"><block type="jikko_digital_write"><field name="PIN">13</field><field name="STATE">HIGH</field><next><block type="jikko_delay"><value name="SEC"><shadow type="math_number"><field name="NUM">1</field></shadow></value><next><block type="jikko_digital_write"><field name="PIN">13</field><field name="STATE">LOW</field><next><block type="jikko_delay"><value name="SEC"><shadow type="math_number"><field name="NUM">1</field></shadow></value></block></next></block></next></block></next></block></statement></block></next></block></xml>`;Blockly.Xml.domToWorkspace(Blockly.utils.xml.textToDom(x),ws)}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(e.t);e.t=setTimeout(()=>e.classList.remove('show'),2200)}
const safe=(s,f='value')=>{const x=String(s||'').replace(/[^A-Za-z0-9_]/g,'_').replace(/^([0-9])/,'_$1');return x&&!/^_+$/.test(x)?x:f};
function mapVars(){vars=new Map();let i=1;ws.getAllVariables().forEach(v=>vars.set(v.getId(),safe(v.name,'value'+i++)))}
function vname(b){const f=b.getField('VAR'),m=f&&f.getVariable?f.getVariable():null;return m?(vars.get(m.getId())||safe(m.name)):'value'}
function val(b,nm,d='0'){const x=b.getInputTargetBlock(nm);return x?expr(x):d}
function expr(b){if(!b)return'0';switch(b.type){case'math_number':return String(Number(b.getFieldValue('NUM'))||0);case'text':return JSON.stringify(b.getFieldValue('TEXT')||'');case'variables_get':return vname(b);case'jikko_analog_read':return`analogRead(${b.getFieldValue('PIN')})`;case'jikko_digital_read':return`(digitalRead(${b.getFieldValue('PIN')}) == HIGH)`;case'jikko_ultra':features.ultra=true;return`readUltrasonic(${b.getFieldValue('TRIG')}, ${b.getFieldValue('ECHO')})`;case'logic_boolean':return b.getFieldValue('BOOL')==='TRUE'?'true':'false';case'logic_negate':return`!(${val(b,'BOOL','false')})`;case'logic_operation':return`(${val(b,'A','false')} ${b.getFieldValue('OP')==='AND'?'&&':'||'} ${val(b,'B','false')})`;case'logic_compare':return`(${val(b,'A')} ${{EQ:'==',NEQ:'!=',LT:'<',LTE:'<=',GT:'>',GTE:'>='}[b.getFieldValue('OP')]||'=='} ${val(b,'B')})`;case'math_arithmetic':{const o=b.getFieldValue('OP');if(o==='POWER')return`pow(${val(b,'A')}, ${val(b,'B')})`;return`(${val(b,'A')} ${{ADD:'+',MINUS:'-',MULTIPLY:'*',DIVIDE:'/'}[o]||'+'} ${val(b,'B')})`}case'text_join':{let a=[];for(let i=0;b.getInput('ADD'+i);i++)a.push(val(b,'ADD'+i,'""'));return a.length?a.join(' + '):'String("")'}default:return'0'}}
function chain(b,i='  '){let c='';while(b){c+=stmt(b,i);b=b.getNextBlock()}return c}
function stmt(b,i){switch(b.type){case'jikko_start':case'jikko_lcd_begin':case'jikko_pixel_begin':case'jikko_serial_begin':return'';case'jikko_delay':return`${i}delay((unsigned long)(1000 * ${val(b,'SEC','1')}));\n`;case'jikko_repeat':{const x=safe(b.id.slice(0,5),'i');return`${i}for(int repeat_${x}=0; repeat_${x}<${val(b,'TIMES','10')}; repeat_${x}++){\n${chain(b.getInputTargetBlock('DO'),i+'  ')}${i}}\n`}case'jikko_forever':return`${i}while(true){\n${chain(b.getInputTargetBlock('DO'),i+'  ')}${i}}\n`;case'jikko_if':return`${i}if(${val(b,'COND','false')}){\n${chain(b.getInputTargetBlock('DO'),i+'  ')}${i}}\n`;case'jikko_if_else':return`${i}if(${val(b,'COND','false')}){\n${chain(b.getInputTargetBlock('DO'),i+'  ')}${i}}else{\n${chain(b.getInputTargetBlock('ELSE'),i+'  ')}${i}}\n`;case'jikko_wait_until':return`${i}while(!(${val(b,'COND','false')})){delay(1);}\n`;case'jikko_repeat_until':return`${i}while(!(${val(b,'COND','false')})){\n${chain(b.getInputTargetBlock('DO'),i+'  ')}${i}}\n`;case'jikko_digital_write':return`${i}digitalWrite(${b.getFieldValue('PIN')}, ${b.getFieldValue('STATE')});\n`;case'jikko_pwm_write':return`${i}analogWrite(${b.getFieldValue('PIN')}, constrain(${val(b,'VALUE')},0,255));\n`;case'jikko_servo':return`${i}servo_${b.getFieldValue('PIN')}.write(constrain(${val(b,'ANGLE','90')},0,180));\n`;case'jikko_tone':return`${i}tone(${b.getFieldValue('PIN')}, ${val(b,'FREQ','262')});\n`;case'jikko_notone':return`${i}noTone(${b.getFieldValue('PIN')});\n`;case'variables_set':return`${i}${vname(b)} = ${val(b,'VALUE')};\n`;case'jikko_lcd_print':return`${i}lcd.setCursor(${val(b,'COL')},${val(b,'ROW')});\n${i}lcd.print(${val(b,'TEXT','""')});\n`;case'jikko_lcd_clear':return`${i}lcd.clear();\n`;case'jikko_pixel_set':return`${i}pixels.setPixelColor(${val(b,'INDEX')}, pixels.Color(${val(b,'R')},${val(b,'G')},${val(b,'B')}));\n`;case'jikko_pixel_show':return`${i}pixels.show();\n`;case'jikko_serial_print':return`${i}Serial.println(${val(b,'TEXT','""')});\n`;default:return''}}
function code(){mapVars();features={servo:new Set,outs:new Set,ins:new Set,baud:null,lcd:null,pixel:null,ultra:false,pairs:[]};const all=ws.getAllBlocks(false);all.forEach(b=>{const p=b.getFieldValue&&b.getFieldValue('PIN');if(['jikko_digital_write','jikko_pwm_write'].includes(b.type))features.outs.add(p);if(b.type==='jikko_digital_read')features.ins.add(p);if(b.type==='jikko_servo')features.servo.add(p);if(b.type==='jikko_serial_begin')features.baud=b.getFieldValue('BAUD');if(b.type==='jikko_serial_print'&&!features.baud)features.baud='9600';if(b.type==='jikko_lcd_begin')features.lcd=b.getFieldValue('ADDR');if(['jikko_lcd_print','jikko_lcd_clear'].includes(b.type)&&!features.lcd)features.lcd='0x27';if(b.type==='jikko_pixel_begin')features.pixel={pin:p,count:val(b,'COUNT','8')};if(['jikko_pixel_set','jikko_pixel_show'].includes(b.type)&&!features.pixel)features.pixel={pin:'6',count:'8'};if(b.type==='jikko_ultra')features.pairs.push([b.getFieldValue('TRIG'),b.getFieldValue('ECHO')])});let inc=[],dec=[],setup=[],help=[];if(features.servo.size){inc.push('#include <Servo.h>');features.servo.forEach(p=>{dec.push(`Servo servo_${p};`);setup.push(`  servo_${p}.attach(${p});`)})}if(features.lcd){inc.push('#include <Wire.h>','#include <LiquidCrystal_I2C.h>');dec.push(`LiquidCrystal_I2C lcd(${features.lcd},16,2);`);setup.push('  lcd.init();','  lcd.backlight();')}if(features.pixel){inc.push('#include <Adafruit_NeoPixel.h>');dec.push(`Adafruit_NeoPixel pixels(${features.pixel.count},${features.pixel.pin},NEO_GRB + NEO_KHZ800);`);setup.push('  pixels.begin();','  pixels.show();')}if(features.baud)setup.push(`  Serial.begin(${features.baud});`);features.outs.forEach(p=>p&&setup.push(`  pinMode(${p}, OUTPUT);`));features.ins.forEach(p=>p&&setup.push(`  pinMode(${p}, INPUT);`));features.pairs.forEach(([t,e])=>setup.push(`  pinMode(${t}, OUTPUT);`,`  pinMode(${e}, INPUT);`));if(features.pairs.length)help.push('long readUltrasonic(int t,int e){digitalWrite(t,LOW);delayMicroseconds(2);digitalWrite(t,HIGH);delayMicroseconds(10);digitalWrite(t,LOW);unsigned long d=pulseIn(e,HIGH,30000UL);return d==0?0:(long)(d*0.0343/2.0);}');ws.getAllVariables().forEach(m=>dec.push(`long ${vars.get(m.getId())}=0;`));let loop='';ws.getTopBlocks(true).forEach(t=>loop+=t.type==='jikko_start'?chain(t.getNextBlock()):chain(t));if(!loop.trim())loop='  // 블록을 연결하세요.\n';const uniq=a=>[...new Set(a)].join('\n');const out=[uniq(inc),uniq(dec),help.join('\n\n'),`void setup(){\n${uniq(setup)}\n}`,`void loop(){\n${loop}}`].filter(x=>x.trim()).join('\n\n')+'\n';$('#code').value=out;return out}
function state(){return{version:2,name:$('#name').value,board:$('#board').value,workspace:Blockly.serialization.workspaces.save(ws)}}
function save(){localStorage.setItem('jikkolab.blockly.v2',JSON.stringify(state()))}
function load(s){if(!s||!s.workspace)throw Error('지원하지 않는 프로젝트입니다.');ws.clear();Blockly.serialization.workspaces.load(s.workspace,ws);$('#name').value=s.name||'프로젝트';$('#board').value=s.board||'uno';code()}
function download(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
async function connect(){if(!navigator.serial)return toast('최신 Chrome 또는 Edge에서 열어주세요.');if(port){await closeSerial();try{await port.close()}catch{}port=null;status();return}try{port=await navigator.serial.requestPort();status();toast('USB 장치를 선택했습니다.')}catch(e){if(e.name!=='NotFoundError')toast(e.message)}}
function status(){$('#status').textContent=port?'USB 선택됨':'연결 안 됨';$('#connect').textContent=port?'🔌 해제':'🔌 연결'}
async function closeSerial(){serialOpen=false;if(reader)try{await reader.cancel()}catch{}await wait(60);if(port&&(port.readable||port.writable))try{await port.close()}catch{}$('#serialOpen').textContent='열기'}
async function serialToggle(){if(!port){await connect();if(!port)return}if(serialOpen)return closeSerial();try{await port.open({baudRate:Number($('#baud').value)});serialOpen=true;$('#serialOpen').textContent='닫기';readLoop()}catch(e){toast(e.message)}}
async function readLoop(){const d=new TextDecoder;try{while(serialOpen&&port.readable){reader=port.readable.getReader();try{while(true){const{value,done}=await reader.read();if(done)break;if(value){$('#serialOut').textContent+=d.decode(value,{stream:true});$('#serialOut').scrollTop=1e9}}}finally{reader.releaseLock();reader=null}}}catch(e){if(serialOpen)toast(e.message)}}
async function send(){if(!serialOpen||!port?.writable)return toast('시리얼 모니터를 먼저 여세요.');const w=port.writable.getWriter();try{await w.write(new TextEncoder().encode($('#serialIn').value+'\r\n'))}finally{w.releaseLock()}}
function parseHex(hex){const m=new Map;let u=0,max=0;for(let l of hex.split(/\r?\n/)){l=l.trim();if(!l)continue;const a=[];for(let i=1;i<l.length;i+=2)a.push(parseInt(l.slice(i,i+2),16));const n=a[0],ad=(a[1]<<8)|a[2],t=a[3],d=a.slice(4,4+n);if(t===0){const b=u+ad;d.forEach((v,i)=>m.set(b+i,v));max=Math.max(max,b+d.length)}else if(t===4)u=((d[0]<<8)|d[1])<<16;else if(t===1)break}const o=new Uint8Array(max);o.fill(255);m.forEach((v,k)=>o[k]=v);return o}
class Upload{constructor(p,f){this.p=p;this.f=f;this.q=[]}async open(b){await this.p.open({baudRate:b,bufferSize:65536});this.r=this.p.readable.getReader();this.w=this.p.writable.getWriter()}async close(){try{this.r.releaseLock();this.w.releaseLock()}catch{}try{await this.p.close()}catch{}}async rb(){if(this.q.length)return this.q.shift();const z=await Promise.race([this.r.read(),new Promise((_,j)=>setTimeout(()=>j(Error('Arduino 응답 시간 초과')),1800))]);this.q.push(...z.value);return this.q.shift()}async cmd(a){await this.w.write(Uint8Array.from([...a,32]));if(await this.rb()!==20||await this.rb()!==16)throw Error('부트로더 응답 오류')}async run(data,baud){await this.open(baud);try{try{await this.p.setSignals({dataTerminalReady:false,requestToSend:false});await wait(120);await this.p.setSignals({dataTerminalReady:true,requestToSend:true})}catch{}await wait(700);for(let i=0;i<8;i++){try{await this.cmd([48]);break}catch{if(i===7)throw Error('보드와 동기화하지 못했습니다.')}}await this.cmd([80]);for(let o=0;o<data.length;o+=128){const p=data.slice(o,o+128),w=o>>1;await this.cmd([85,w&255,w>>8]);await this.cmd([100,p.length>>8,p.length&255,70,...p]);this.f((o+p.length)/data.length*100)}await this.cmd([81])}finally{await this.close()}}}
async function upload(){if(!port){await connect();if(!port)return}if(serialOpen)await closeSerial();const d=$('#progress'),bar=$('#bar');$('#pTitle').textContent='코드 컴파일 중';$('#pText').textContent='Arduino HEX 파일을 만들고 있습니다.';$('#log').textContent='';bar.value=10;d.showModal();try{const k=$('#board').value,fqbn={uno:'arduino:avr:uno',nano:'arduino:avr:nano:cpu=atmega328',nano_old:'arduino:avr:nano:cpu=atmega328old'}[k],source=code(),r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source,code:source,fqbn,board:k})}),j=await r.json(),hex=j.hex||j.data?.hex||j.result?.hex;if(!r.ok||!hex)throw Error(j.error||j.detail||'컴파일 서버에서 HEX를 받지 못했습니다.');$('#pTitle').textContent='아두이노 업로드 중';$('#pText').textContent='USB 케이블을 분리하지 마세요.';bar.value=35;await new Upload(port,p=>bar.value=35+p*.65).run(parseHex(hex),k==='nano_old'?57600:115200);bar.value=100;$('#pTitle').textContent='업로드 완료';$('#pText').textContent='프로그램이 실행됩니다.'}catch(e){bar.value=0;$('#pTitle').textContent='업로드 실패';$('#pText').textContent=e.message;$('#log').textContent=e.stack||e}}
function ui(){$('#connect').onclick=connect;$('#upload').onclick=upload;$('#undo').onclick=()=>ws.undo(false);$('#redo').onclick=()=>ws.undo(true);$('#clear').onclick=()=>confirm('모든 블록을 지울까요?')&&ws.clear();$('#center').onclick=()=>ws.scrollCenter();$('#copy').onclick=()=>navigator.clipboard.writeText($('#code').value).then(()=>toast('코드를 복사했습니다.'));$('#ino').onclick=()=>download(($('#name').value||'project')+'.ino',code());$('#save').onclick=()=>download(($('#name').value||'project')+'.jikko',JSON.stringify(state(),null,2),'application/json');$('#open').onclick=()=>$('#file').click();$('#file').onchange=async e=>{try{if(e.target.files[0]){load(JSON.parse(await e.target.files[0].text()));save();toast('프로젝트를 불러왔습니다.')}}catch(x){toast(x.message)}e.target.value=''};$('#serialOpen').onclick=serialToggle;$('#serialClear').onclick=()=>$('#serialOut').textContent='';$('#send').onclick=send;$('#serialIn').onkeydown=e=>e.key==='Enter'&&send();$('#closeProgress').onclick=()=>$('#progress').close();$('#name').onchange=save;$('#board').onchange=save;$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));document.body.dataset.view=b.dataset.view;setTimeout(()=>Blockly.svgResize(ws),50)})}
function init(){blocks();ws=Blockly.inject('blocklyDiv',{toolbox:toolbox(),renderer:'zelos',theme:theme(),trashcan:true,sounds:false,move:{scrollbars:true,drag:true,wheel:true},zoom:{controls:true,wheel:true,startScale:.92,maxScale:1.45,minScale:.48,scaleSpeed:1.12,pinch:true},grid:{spacing:22,length:1,colour:'#DDE3E9',snap:false}});const s=localStorage.getItem('jikkolab.blockly.v2');if(s)try{load(JSON.parse(s))}catch{defaultBlocks()}else defaultBlocks();ws.addChangeListener(e=>{if(e.isUiEvent)return;code();clearTimeout(saveTimer);saveTimer=setTimeout(save,250)});ui();status();code();addEventListener('resize',()=>Blockly.svgResize(ws))}
window.Blockly?init():document.body.innerHTML='<p style="padding:30px">블록 편집기를 불러오지 못했습니다. 새로고침해 주세요.</p>';
