'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],wait=ms=>new Promise(r=>setTimeout(r,ms));
const API='https://arduino-cli-python-363946744577.asia-northeast3.run.app/compile';
const COLORS={event:'#f1bc35',control:'#efa92e',pin:'#df3e42',motor:'#9946cc',input:'#5961df',variable:'#53616b',serial:'#8c5bdf'};
const CATS=[['event','이벤트'],['control','제어'],['pin','핀'],['motor','모터'],['input','입력'],['variable','변수'],['serial','시리얼']];
const DEF={
 start:{c:'event',text:'시작하기'},delay:{c:'control',text:'%n 초 기다리기',f:{n:{t:'number',v:1}}},repeat:{c:'control',text:'%n 번 반복하기',f:{n:{t:'number',v:10}},child:1},forever:{c:'control',text:'무한 반복하기',child:1},
 high:{c:'pin',text:'디지털 핀 %pin 켜기',f:{pin:{t:'select',v:'13',o:['2','3','4','5','6','7','8','9','10','11','12','13']}}},low:{c:'pin',text:'디지털 핀 %pin 끄기',f:{pin:{t:'select',v:'13',o:['2','3','4','5','6','7','8','9','10','11','12','13']}}},pwm:{c:'pin',text:'PWM 핀 %pin 값을 %value 로 설정',f:{pin:{t:'select',v:'9',o:['3','5','6','9','10','11']},value:{t:'number',v:128}}},
 servo:{c:'motor',text:'서보모터 핀 %pin 각도 %angle 도',f:{pin:{t:'select',v:'9',o:['2','3','4','5','6','7','8','9','10','11','12','13']},angle:{t:'number',v:90}}},
 analog:{c:'input',text:'변수 %name 에 아날로그 핀 %pin 값 저장',f:{name:{t:'text',v:'센서값'},pin:{t:'select',v:'A0',o:['A0','A1','A2','A3','A4','A5']}}},digital:{c:'input',text:'변수 %name 에 디지털 핀 %pin 값 저장',f:{name:{t:'text',v:'입력값'},pin:{t:'select',v:'2',o:['2','3','4','5','6','7','8','9','10','11','12','13']}}},
 setvar:{c:'variable',text:'변수 %name 를 %value 로 정하기',f:{name:{t:'text',v:'값'},value:{t:'number',v:0}}},serialBegin:{c:'serial',text:'시리얼 통신 시작 %baud bps',f:{baud:{t:'select',v:'9600',o:['9600','57600','115200']}}},serialPrint:{c:'serial',text:'시리얼에 %text 출력',f:{text:{t:'text',v:'안녕하세요'}}}
};
let program=[],history=[],future=[],selectedCat='event',port=null,serialOpen=false,reader=null;
const id=()=>Math.random().toString(36).slice(2,10),clone=o=>JSON.parse(JSON.stringify(o));
function block(type){let d=DEF[type],f={};Object.entries(d.f||{}).forEach(([k,v])=>f[k]=v.v);return{id:id(),type,f,children:d.child?[]:undefined}}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(e.t);e.t=setTimeout(()=>e.classList.remove('show'),2200)}
function snap(){history.push(JSON.stringify(program));if(history.length>50)history.shift();future=[]}
function commit(){render();generate();localStorage.setItem('jikkolab.project',JSON.stringify({program,name:$('#name').value,board:$('#board').value}))}
function mutate(fn){snap();fn();commit()}
function renderCats(){let c=$('#cats');c.innerHTML='';CATS.forEach(([key,name])=>{let b=document.createElement('button');b.className='cat'+(key===selectedCat?' active':'');b.innerHTML=`<i style="background:${COLORS[key]}"></i><span>${name}</span>`;b.onclick=()=>{selectedCat=key;renderCats();renderPalette()};c.appendChild(b)})}
function renderPalette(){let box=$('#palette');box.innerHTML='';$('#catTitle').textContent=CATS.find(x=>x[0]===selectedCat)[1];Object.entries(DEF).filter(([,d])=>d.c===selectedCat).forEach(([type,d])=>{let b=document.createElement('button');b.className='sample';b.style.background=COLORS[d.c];b.textContent=d.text.replace(/%\w+/g,'○');b.onclick=()=>mutate(()=>program.push(block(type)));box.appendChild(b)})}
function find(list,bid){for(let i=0;i<list.length;i++){if(list[i].id===bid)return{list,i,b:list[i]};let r=list[i].children&&find(list[i].children,bid);if(r)return r}return null}
function fieldEl(spec,val,onchange){let e;if(spec.t==='select'){e=document.createElement('select');spec.o.forEach(o=>{let x=document.createElement('option');x.value=o;x.textContent=o;e.appendChild(x)});e.value=val}else{e=document.createElement('input');e.type=spec.t;e.value=val;if(spec.t==='number')e.inputMode='decimal'}e.onchange=()=>onchange(e.value);e.onclick=x=>x.stopPropagation();return e}
function renderBlock(b){let d=DEF[b.type],el=document.createElement('div');el.className='block'+(d.child?' control':'');el.style.background=COLORS[d.c];el.style.setProperty('--c',COLORS[d.c]);let face=document.createElement('div');face.className='face';let parts=d.text.split(/(%\w+)/);parts.forEach(p=>{if(p[0]==='%'){let k=p.slice(1);face.appendChild(fieldEl(d.f[k],b.f[k],v=>{b.f[k]=v;commit()}))}else face.append(document.createTextNode(p))});let acts=document.createElement('span');acts.className='actions';[['↑',-1],['↓',1],['×',0]].forEach(([t,dir])=>{let x=document.createElement('button');x.textContent=t;x.onclick=e=>{e.stopPropagation();let r=find(program,b.id);if(!r)return;if(!dir)mutate(()=>r.list.splice(r.i,1));else mutate(()=>{let ni=Math.max(0,Math.min(r.list.length-1,r.i+dir));let z=r.list.splice(r.i,1)[0];r.list.splice(ni,0,z)})};acts.appendChild(x)});face.appendChild(acts);el.appendChild(face);if(d.child){let ch=document.createElement('div');ch.className='children';b.children.forEach(x=>ch.appendChild(renderBlock(x)));ch.onclick=e=>{if(e.target===ch){e.stopPropagation();let type=prompt('안에 추가할 블록 이름: high, low, delay, pwm, servo, serialPrint','delay');if(DEF[type])mutate(()=>b.children.push(block(type)))}};el.appendChild(ch)}return el}
function render(){let root=$('#program');root.innerHTML='';program.forEach(b=>root.appendChild(renderBlock(b)));$('#guide').style.display=program.length?'none':'flex'}
function esc(s){return JSON.stringify(String(s))}
function genList(list,indent='  '){let out='';for(let b of list){let f=b.f||{};switch(b.type){case'delay':out+=`${indent}delay(${Math.round(Number(f.n)*1000)});\n`;break;case'high':out+=`${indent}digitalWrite(${f.pin}, HIGH);\n`;break;case'low':out+=`${indent}digitalWrite(${f.pin}, LOW);\n`;break;case'pwm':out+=`${indent}analogWrite(${f.pin}, ${Number(f.value)});\n`;break;case'servo':out+=`${indent}servo_${f.pin}.write(${Number(f.angle)});\n`;break;case'analog':out+=`${indent}int ${safe(f.name)} = analogRead(${f.pin});\n`;break;case'digital':out+=`${indent}int ${safe(f.name)} = digitalRead(${f.pin});\n`;break;case'setvar':out+=`${indent}int ${safe(f.name)} = ${Number(f.value)};\n`;break;case'serialPrint':out+=`${indent}Serial.println(${esc(f.text)});\n`;break;case'repeat':out+=`${indent}for(int i=0;i<${Number(f.n)};i++){\n${genList(b.children,indent+'  ')}${indent}}\n`;break;case'forever':out+=`${indent}while(true){\n${genList(b.children,indent+'  ')}${indent}}\n`;break}}return out}
function safe(s){return(String(s||'value').replace(/[^A-Za-z0-9_가-힣]/g,'_'))}
function generate(){let setup=[],servos=new Set(),begun=false;function scan(list){list.forEach(b=>{let f=b.f||{};if(['high','low'].includes(b.type))setup.push(`  pinMode(${f.pin}, OUTPUT);`);if(b.type==='pwm')setup.push(`  pinMode(${f.pin}, OUTPUT);`);if(b.type==='servo'){servos.add(f.pin);setup.push(`  servo_${f.pin}.attach(${f.pin});`)}if(b.type==='serialBegin'){setup.push(`  Serial.begin(${f.baud});`);begun=true}if(b.type==='digital')setup.push(`  pinMode(${f.pin}, INPUT);`);if(b.children)scan(b.children)})}scan(program);let inc=servos.size?'#include <Servo.h>\n':'';let decl=[...servos].map(p=>`Servo servo_${p};`).join('\n');let body=genList(program.filter(b=>!['start','serialBegin'].includes(b.type)));if(!begun&&program.some(b=>b.type==='serialPrint'))setup.push('  Serial.begin(9600);');$('#code').value=`${inc}${decl}${decl?'\n\n':''}void setup(){\n${[...new Set(setup)].join('\n')}\n}\n\nvoid loop(){\n${body||'  // 블록을 추가하세요.\n'}}\n`;return $('#code').value}
function download(name,text,type='text/plain'){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
async function connect(){if(!navigator.serial){toast('최신 Chrome/Edge에서 열어주세요.');return}if(port){await closeSerial();try{await port.close()}catch{}port=null;status();return}try{port=await navigator.serial.requestPort();status();toast('USB 장치를 선택했습니다.')}catch(e){if(e.name!=='NotFoundError')toast(e.message)}}
function status(){$('#status').textContent=port?'USB 선택됨':'연결 안 됨';$('#connect').textContent=port?'🔌 해제':'🔌 연결'}
async function closeSerial(){serialOpen=false;if(reader)try{await reader.cancel()}catch{}await wait(60);if(port?.readable||port?.writable)try{await port.close()}catch{}$('#serialOpen').textContent='열기'}
async function serialToggle(){if(!port)return connect();if(serialOpen){await closeSerial();return}try{await port.open({baudRate:Number($('#baud').value)});serialOpen=true;$('#serialOpen').textContent='닫기';readLoop()}catch(e){toast(e.message)}}
async function readLoop(){let dec=new TextDecoder();try{while(serialOpen&&port.readable){reader=port.readable.getReader();try{while(true){let{value,done}=await reader.read();if(done)break;if(value){$('#serialOut').textContent+=dec.decode(value,{stream:true});$('#serialOut').scrollTop=1e9}}}finally{reader.releaseLock();reader=null}}}catch(e){if(serialOpen)toast(e.message)}}
async function send(){if(!serialOpen||!port?.writable)return toast('시리얼 모니터를 먼저 여세요.');let w=port.writable.getWriter();try{await w.write(new TextEncoder().encode($('#serialIn').value+'\r\n'))}finally{w.releaseLock()}}
function parseHex(hex){let m=new Map(),upper=0,max=0;for(let line of hex.split(/\r?\n/)){line=line.trim();if(!line)continue;let a=[];for(let i=1;i<line.length;i+=2)a.push(parseInt(line.slice(i,i+2),16));let len=a[0],addr=(a[1]<<8)|a[2],type=a[3],data=a.slice(4,4+len);if(type===0){let base=upper+addr;data.forEach((v,i)=>m.set(base+i,v));max=Math.max(max,base+data.length)}else if(type===4)upper=((data[0]<<8)|data[1])<<16;else if(type===1)break}let out=new Uint8Array(max);out.fill(255);m.forEach((v,k)=>out[k]=v);return out}
class Uploader{constructor(p,prog){this.p=p;this.prog=prog;this.rx=[]}async open(baud){await this.p.open({baudRate:baud,bufferSize:65536});this.r=this.p.readable.getReader();this.w=this.p.writable.getWriter()}async close(){try{this.r.releaseLock();this.w.releaseLock()}catch{}try{await this.p.close()}catch{}}async rb(){if(this.rx.length)return this.rx.shift();let{value}=await Promise.race([this.r.read(),new Promise((_,j)=>setTimeout(()=>j(Error('Arduino 응답 시간 초과')),1500))]);this.rx.push(...value);return this.rx.shift()}async cmd(a){await this.w.write(Uint8Array.from([...a,32]));let x=await this.rb(),y=await this.rb();if(x!==20||y!==16)throw Error('부트로더 응답 오류')}async upload(data,baud){await this.open(baud);try{try{await this.p.setSignals({dataTerminalReady:false,requestToSend:false});await wait(120);await this.p.setSignals({dataTerminalReady:true,requestToSend:true})}catch{}await wait(700);for(let i=0;i<8;i++){try{await this.cmd([48]);break}catch{if(i===7)throw Error('보드와 동기화하지 못했습니다.')}}await this.cmd([80]);for(let o=0;o<data.length;o+=128){let c=data.slice(o,o+128),word=o>>1;await this.cmd([85,word&255,word>>8]);await this.cmd([100,c.length>>8,c.length&255,70,...c]);this.prog((o+c.length)/data.length*100)}await this.cmd([81])}finally{await this.close()}}}
async function upload(){if(!port){await connect();if(!port)return}if(serialOpen)await closeSerial();let d=$('#progress'),bar=$('#bar');$('#pTitle').textContent='코드 컴파일 중';$('#pText').textContent='클라우드에서 HEX 파일을 만들고 있습니다.';$('#log').textContent='';bar.value=10;d.showModal();try{let key=$('#board').value,fqbn={uno:'arduino:avr:uno',nano:'arduino:avr:nano:cpu=atmega328',nano_old:'arduino:avr:nano:cpu=atmega328old'}[key],source=generate();let res=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source,fqbn,code:source,board:key})}),json=await res.json();let hex=json.hex||json.data?.hex||json.result?.hex;if(!res.ok||!hex)throw Error(json.error||json.detail||'컴파일 서버 응답에 HEX가 없습니다.');$('#pTitle').textContent='아두이노 업로드 중';$('#pText').textContent='USB 케이블을 분리하지 마세요.';bar.value=35;let bytes=parseHex(hex),up=new Uploader(port,p=>bar.value=35+p*.65);await up.upload(bytes,key==='nano_old'?57600:115200);bar.value=100;$('#pTitle').textContent='업로드 완료';$('#pText').textContent='프로그램이 실행됩니다.'}catch(e){bar.value=0;$('#pTitle').textContent='업로드 실패';$('#pText').textContent=e.message;$('#log').textContent=e.stack||e}}
function init(){renderCats();renderPalette();try{let s=JSON.parse(localStorage.getItem('jikkolab.project'));if(s){program=s.program||[];$('#name').value=s.name||'새 프로젝트';$('#board').value=s.board||'uno'}}catch{}if(!program.length){let f=block('forever');f.children=[block('high'),block('delay'),block('low'),block('delay')];program=[block('start'),f]}commit();$('#connect').onclick=connect;$('#upload').onclick=upload;$('#clear').onclick=()=>mutate(()=>program=[]);$('#undo').onclick=()=>{if(!history.length)return;future.push(JSON.stringify(program));program=JSON.parse(history.pop());commit()};$('#redo').onclick=()=>{if(!future.length)return;history.push(JSON.stringify(program));program=JSON.parse(future.pop());commit()};$('#save').onclick=()=>download(($('#name').value||'project')+'.jikko',JSON.stringify({program,name:$('#name').value,board:$('#board').value},null,2),'application/json');$('#open').onclick=()=>$('#file').click();$('#file').onchange=async e=>{try{let s=JSON.parse(await e.target.files[0].text());program=s.program||[];$('#name').value=s.name||'불러온 프로젝트';$('#board').value=s.board||'uno';commit()}catch{toast('프로젝트 파일을 열 수 없습니다.')}};$('#ino').onclick=()=>download(($('#name').value||'project')+'.ino',generate());$('#copy').onclick=()=>navigator.clipboard.writeText($('#code').value).then(()=>toast('코드를 복사했습니다.'));$('#serialOpen').onclick=serialToggle;$('#serialClear').onclick=()=>$('#serialOut').textContent='';$('#send').onclick=send;$('#closeProgress').onclick=()=>$('#progress').close();$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));document.body.dataset.view=b.dataset.view});$('#name').onchange=commit;$('#board').onchange=commit;status()}
init();
